site_name: Cops and Robbers
nav:
    - Home: index.md
    - Classes: Classes/index.md
    - Examples: Examples/index.md
    - Modules: Modules/index.md
    - Namespaces: Namespaces/index.md
    palette:
        - scheme: default
          primary: blue
          accent: light blue
extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/DerangedSenators
          name: DerangedSenators on Github
copyright: Copyright &copy; 2020 Deranged Senators
